language: node_js

services:
  - docker

node_js:
  - "6"

sudo: false

before_install:
  # Skip SauceLabs tests in Pull Request
  - |
    if [[ $TRAVIS_SECURE_ENV_VARS == "false"  ]] && [[ $CLIENT == saucelabs:* ]]; then
      echo "Not running test, cannot connect to SauceLabs in Pull Request"
      travis_terminate 0
    fi

  # Install PhantomJS and cache it
  # See https://github.com/Medium/phantomjs#continuous-integration
  - "export PHANTOMJS_VERSION=2.1.1"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"

  # package-lock.json was introduced in npm@5
  - npm install -g npm@5 # skip this if you are using node 9
  - npm install -g greenkeeper-lockfile@1

before_script:
  # update package-lock.json
  - greenkeeper-lockfile-update
  # run linter before the tests
  - npm run lint

after_script:
  # upload the updated package-lock.json
  - greenkeeper-lockfile-upload

script: npm run $COMMAND

env:
  global:
  - NPM_CONFIG_PROGRESS="false"
  - secure: "U7yqHtQrvzNob8YMh9iH34piyr4N0ZoX/G45VUuGlOoXe2gjhwHMAERRISZLtdzHawYu780SZ7g42HP2jsgwXqGGUmxLNMTFY44V19030Fn2QFEIZ30Ni/t0VRpvt1gwiAwRQJlVyKxS4B6qctf6HGm+hS2gQHnGuj4uX9WMZ8A="
  - secure: "LjHjFT855IQ66dfXDroe5fmsBNohyO7j5M0sEHOaNvtqnVYVAfMgwW3JpESXhXY0mEgSSKSOtCEGK2iqhsGL1ou4nYP0TarV/aKBjclNotMWcBI+VdgvooCtV4D2LCmFWqJ8agxZnmkeqX+VmnMieEttZAcagXslcNARq96m9v0="
  - secure: "UqQRT/Fn3cIHWXd9quN0mFD4BG8WeyxJKlghPXF+q3BZOeRyXe4FpG7RJBQohGHvJYzPY27Yi7mIlEOLCICFtC0Os/qNueK11/D+J6Zhr8rPqi/JTUJth0ybwhSBXyb6Vfm4Ce4m8hfKfLHTbo5FP533RuIUhPrThO3+APpxdCo="

  matrix:
  - SERVER=couchdb:latest CLIENT=node COMMAND=test
  - SERVER=couchdb:latest CLIENT=phantom COMMAND=test

  - SERVER=couchdb:1.7.1 CLIENT=node COMMAND=test
  - SERVER=couchdb:1.7.1 CLIENT=phantom COMMAND=test

  - SERVER=pouchdb-server CLIENT=node COMMAND=test
  - SERVER=pouchdb-server CLIENT=phantom COMMAND=test

  - SERVER=couchdb:latest CLIENT=saucelabs:Chrome COMMAND=test
  - SERVER=couchdb:latest CLIENT=saucelabs:Firefox COMMAND=test
  - SERVER=couchdb:latest CLIENT=saucelabs:Safari:7 COMMAND=test
  - SERVER=couchdb:latest CLIENT="saucelabs:Internet Explorer:10:Windows 8" COMMAND=test
  - SERVER=couchdb:latest CLIENT="saucelabs:Internet Explorer:11:Windows 10" COMMAND=test

matrix:
  allow_failures:
    # Waiting for pouchdb/pouchdb#6814
    - env: SERVER=couchdb:latest CLIENT=node COMMAND=test
    - env: SERVER=couchdb:1.7.1 CLIENT=node COMMAND=test
    - env: SERVER=pouchdb-server CLIENT=node COMMAND=test
    # Waiting for pouchdb/pouchdb#6855
    - env: SERVER=couchdb:latest CLIENT="saucelabs:Internet Explorer:11:Windows 10" COMMAND=test

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache:
  directories:
  - $HOME/.npm
  # See https://github.com/Medium/phantomjs#continuous-integration
  - travis_phantomjs